# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        vignette:
            quality: 50
            filters:
                thumbnail: { size: [70, 70], mode: outbound }
        paysage:
            quality: 95
            filters:
                thumbnail: { size: [700, 100], mode: outbound }
